MATRIKS TRANSFORMASI TRANSLASI

In [134]:
import numpy as np

def translate_2d(x, y, tx, ty):
    # Matriks awal
    initial_matrix = np.array([
        [x],
        [y],
        [1]
    ])

    # Matriks translasi 2D
    translation_matrix = np.array([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1]
    ])

    # Mencetak P
    print("\n Matriks P(x,y)")
    print(initial_matrix)

    # Mencetak matriks transformasi translasi
    print("\nMatriks Transformasi Translasi:")
    print(translation_matrix)

    # Mencetak matriks hasil transformasi translasi (tanpa matriks awal)
    result_matrix = np.dot(translation_matrix, initial_matrix)
    print("\nMatriks Hasil Transformasi Translasi:")
    print(result_matrix)

    # Mengembalikan hasil translasi (koordinat x, y)
    return result_matrix[0, 0], result_matrix[1, 0]

# Input dari pengguna
x = int(input("Masukkan nilai x: "))
y = int(input("Masukkan nilai y: "))
tx = int(input("Masukkan nilai tx: "))
ty = int(input("Masukkan nilai ty: "))

result_x, result_y = translate_2d(x, y, tx, ty)

print(f"\ntranslasi: ({result_x}, {result_y})")


Masukkan nilai x: 3
Masukkan nilai y: 1
Masukkan nilai tx: 2
Masukkan nilai ty: 3

P:
[[3]
 [1]
 [1]]

Matriks Transformasi Translasi:
[[1 0 2]
 [0 1 3]
 [0 0 1]]

Matriks Hasil Transformasi Translasi:
[[5]
 [4]
 [1]]

translasi: (5, 4)


MATRIKS TRANFORMASI ROTASI

In [26]:
import numpy as np
import math

In [135]:

def rotate_2d(x, y, theta):
    #Matriks awal
    initial_matrix = np.array([
        [x],
        [y],
        [1]
    ])

    #Matriks rotasi 2D
    rotation_matrix = np.array([
        [math.cos(theta), -math.sin(theta), 0],
        [math.sin(theta), math.cos(theta), 0],
        [0, 0, 1]
    ])

    # Mencetak P
    print("Matriks P(x,y) = ")
    print((initial_matrix))

    #perkalian matriks
    result_matrix = np.dot(rotation_matrix, initial_matrix)

    #matriks hasil transformasi rotasi
    transformation_matrix = (rotation_matrix)
    print("\n Hasil Matriks Transformasi :")
    print(transformation_matrix)

    #Mengembalikan hasil rotasi (koordinat x, y)
    return result_matrix[0, 0], result_matrix[1, 0]

#implementasi
x = 2
y = 3
theta = math.radians(30)  #Mengubah sudut ke radian

result_x, result_y = rotate_2d(x, y, theta)

print(f"\nSesudah rotasi: ({result_x}, {result_y})")

Matriks P(x,y) = 
[[2]
 [3]
 [1]]

 Hasil Matriks Transformasi :
[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]

Sesudah rotasi: (0.23205080756887764, 3.598076211353316)


MATRIKS TRANSFORMASI SKALA

In [78]:
import numpy as np

def scale_2d(x, y, scale_x, scale_y):
    # Matriks transformasi skala 2D
    scale_matrix = np.array([
        [scale_x, 0, 0],
        [0, scale_y, 0],
        [0, 0, 1]
    ])

    # Representasi vektor kolom [x, y, 1]
    vector_column = np.array([
        [x],
        [y],
        [1]
    ])

    # Mencetak matriks awal
    print("Matriks Awal:")
    print(vector_column)

    # Melakukan perkalian matriks
    result_vector = np.dot(scale_matrix, vector_column)

    # Mencetak matriks transformasi skala
    print("\nMatriks Transformasi Skala:")
    print(scale_matrix)

    # Mengembalikan hasil transformasi
    return result_vector[0], result_vector[1]

# Contoh penggunaan
x = 2
y = 3
scale_x = 2
scale_y = 1.5

result_x, result_y = scale_2d(x, y, scale_x, scale_y)

print(f"\nSesudah transformasi: ({result_x}, {result_y})")


Matriks Awal:
[[2]
 [3]
 [1]]

Matriks Transformasi Skala:
[[2.  0.  0. ]
 [0.  1.5 0. ]
 [0.  0.  1. ]]

Sesudah transformasi: ([4.], [4.5])
