MATRIKS TRANSFORMASI 3D (TRANSLASI)

In [1]:
import numpy as np

def translate_3d(x, y, z, tx, ty, tz):
    # Matriks awal
    initial_matrix = np.array([
        [x],
        [y],
        [z],
        [1]
    ])

    # Matriks translasi 3D
    translation_matrix = np.array([
        [1, 0, 0, tx],
        [0, 1, 0, ty],
        [0, 0, 1, tz],
        [0, 0, 0, 1]
    ])

    # Mencetak P
    print("\n Matriks P(x, y, z)")
    print(initial_matrix)

    # Mencetak matriks transformasi translasi
    print("\nMatriks Transformasi Translasi:")
    print(translation_matrix)

    # Mencetak matriks hasil transformasi translasi (tanpa matriks awal)
    result_matrix = np.dot(translation_matrix, initial_matrix)
    print("\nMatriks Hasil Transformasi Translasi:")
    print(result_matrix)

    # Mengembalikan hasil translasi (koordinat x, y, z)
    return result_matrix[0, 0], result_matrix[1, 0], result_matrix[2, 0]

# Input dari pengguna
x = int(input("Masukkan nilai x: "))
y = int(input("Masukkan nilai y: "))
z = int(input("Masukkan nilai z: "))
tx = int(input("Masukkan nilai tx: "))
ty = int(input("Masukkan nilai ty: "))
tz = int(input("Masukkan nilai tz: "))

result_x, result_y, result_z = translate_3d(x, y, z, tx, ty, tz)

print(f"\ntranslasi: ({result_x}, {result_y}, {result_z})")


Masukkan nilai x: 1
Masukkan nilai y: 3
Masukkan nilai z: 6
Masukkan nilai tx: 9
Masukkan nilai ty: 2
Masukkan nilai tz: 4

 Matriks P(x, y, z)
[[1]
 [3]
 [6]
 [1]]

Matriks Transformasi Translasi:
[[1 0 0 9]
 [0 1 0 2]
 [0 0 1 4]
 [0 0 0 1]]

Matriks Hasil Transformasi Translasi:
[[10]
 [ 5]
 [10]
 [ 1]]

translasi: (10, 5, 10)


MATRIKS TRANSFORMASI 3D (SKALA)

In [2]:
import numpy as np

def scale_3d(x, y, z, sx, sy, sz):
    # Matriks awal
    initial_matrix = np.array([
        [x],
        [y],
        [z],
        [1]
    ])

    # Matriks transformasi skala 3D
    scale_matrix = np.array([
        [sx, 0, 0, 0],
        [0, sy, 0, 0],
        [0, 0, sz, 0],
        [0, 0, 0, 1]
    ])

    # Mencetak P
    print("\n Matriks P(x, y, z)")
    print(initial_matrix)

    # Mencetak matriks transformasi skala
    print("\nMatriks Transformasi Skala:")
    print(scale_matrix)

    # Mencetak matriks hasil transformasi skala (tanpa matriks awal)
    result_matrix = np.dot(scale_matrix, initial_matrix)
    print("\nMatriks Hasil Transformasi Skala:")
    print(result_matrix)

    # Mengembalikan hasil skala (koordinat x, y, z)
    return result_matrix[0, 0], result_matrix[1, 0], result_matrix[2, 0]

# Input dari pengguna
x = int(input("Masukkan nilai x: "))
y = int(input("Masukkan nilai y: "))
z = int(input("Masukkan nilai z: "))
sx = float(input("Masukkan nilai skala sx: "))
sy = float(input("Masukkan nilai skala sy: "))
sz = float(input("Masukkan nilai skala sz: "))

result_x, result_y, result_z = scale_3d(x, y, z, sx, sy, sz)

print(f"\nskala: ({result_x}, {result_y}, {result_z})")


Masukkan nilai x: 3
Masukkan nilai y: 6
Masukkan nilai z: 9
Masukkan nilai skala sx: 1
Masukkan nilai skala sy: 2
Masukkan nilai skala sz: 8

 Matriks P(x, y, z)
[[3]
 [6]
 [9]
 [1]]

Matriks Transformasi Skala:
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 8. 0.]
 [0. 0. 0. 1.]]

Matriks Hasil Transformasi Skala:
[[ 3.]
 [12.]
 [72.]
 [ 1.]]

skala: (3.0, 12.0, 72.0)


MATRIKS TRANSFORMASI 3D (ROTASI THD SUMBU RX, RY, RZ)

In [3]:
import numpy as np

def rotate_3d(x, y, z, rx, ry, rz):
    # Matriks awal
    initial_matrix = np.array([
        [x],
        [y],
        [z],
        [1]
    ])

    # Matriks transformasi rotasi Rx
    rotation_matrix_rx = np.array([
        [1, 0, 0, 0],
        [0, np.cos(np.radians(rx)), -np.sin(np.radians(rx)), 0],
        [0, np.sin(np.radians(rx)), np.cos(np.radians(rx)), 0],
        [0, 0, 0, 1]
    ])

    # Matriks transformasi rotasi Ry
    rotation_matrix_ry = np.array([
        [np.cos(np.radians(ry)), 0, np.sin(np.radians(ry)), 0],
        [0, 1, 0, 0],
        [-np.sin(np.radians(ry)), 0, np.cos(np.radians(ry)), 0],
        [0, 0, 0, 1]
    ])

    # Matriks transformasi rotasi Rz
    rotation_matrix_rz = np.array([
        [np.cos(np.radians(rz)), -np.sin(np.radians(rz)), 0, 0],
        [np.sin(np.radians(rz)), np.cos(np.radians(rz)), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

    # Mencetak P
    print("\n Matriks P(x, y, z)")
    print(initial_matrix)

    # Mencetak matriks transformasi rotasi Rx
    print("\nMatriks Transformasi Rotasi Rx:")
    print(rotation_matrix_rx)

    # Mencetak matriks transformasi rotasi Ry
    print("\nMatriks Transformasi Rotasi Ry:")
    print(rotation_matrix_ry)

    # Mencetak matriks transformasi rotasi Rz
    print("\nMatriks Transformasi Rotasi Rz:")
    print(rotation_matrix_rz)

    # Menghitung matriks hasil transformasi rotasi (tanpa matriks awal)
    result_matrix_rx = np.dot(rotation_matrix_rx, initial_matrix)
    result_matrix_ry = np.dot(rotation_matrix_ry, result_matrix_rx)
    result_matrix_rz = np.dot(rotation_matrix_rz, result_matrix_ry)

    print("\nMatriks Hasil Transformasi Rotasi:")
    print(result_matrix_rz)

    # Mengembalikan hasil rotasi (koordinat x, y, z)
    return result_matrix_rz[0, 0], result_matrix_rz[1, 0], result_matrix_rz[2, 0]

# Input dari pengguna
x = int(input("Masukkan nilai x: "))
y = int(input("Masukkan nilai y: "))
z = int(input("Masukkan nilai z: "))
rx = float(input("Masukkan nilai rotasi Rx (derajat): "))
ry = float(input("Masukkan nilai rotasi Ry (derajat): "))
rz = float(input("Masukkan nilai rotasi Rz (derajat): "))

result_x, result_y, result_z = rotate_3d(x, y, z, rx, ry, rz)

print(f"\nrotasi: ({result_x}, {result_y}, {result_z})")


Masukkan nilai x: 5
Masukkan nilai y: 4
Masukkan nilai z: 6
Masukkan nilai rotasi Rx (derajat): 45
Masukkan nilai rotasi Ry (derajat): 25
Masukkan nilai rotasi Rz (derajat): 90

 Matriks P(x, y, z)
[[5]
 [4]
 [6]
 [1]]

Matriks Transformasi Rotasi Rx:
[[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]

Matriks Transformasi Rotasi Ry:
[[ 0.90630779  0.          0.42261826  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.42261826  0.          0.90630779  0.        ]
 [ 0.          0.          0.          1.        ]]

Matriks Transformasi Rotasi Rz:
[[ 6.123234e-17 -1.000000e+00  0.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

Matriks Hasil Transformasi Rotasi: